In [9]:
import os
import pandas as pd

classes = ['SNR', 'AF', 'IAVB', 'LBBB', 'RBBB', 'PAC', 'PVC', 'STD', 'STE']



In [8]:
test_data_dir ='data/test_dataset'
test_label_csv = os.path.join(test_data_dir, 'labels.csv')
# Load the test labels
test_labels = pd.read_csv(test_label_csv)
#show the first few rows
print(test_labels.head())
#unique fold from small to large
print(test_labels['fold'].unique())
#number of samples in each fold
print(test_labels['fold'].value_counts())

  patient_id  PAC  RBBB  LBBB  PVC  STD  AF  IAVB  STE  SNR  fold
0    JS00001    0     1     0    0    0   1     0    0    0     2
1    JS00005    0     0     0    0    1   0     0    0    0     5
2    JS00007    0     0     0    0    0   1     0    0    0     5
3    JS00008    0     0     0    0    0   0     0    0    1     5
4    JS00013    0     0     0    0    0   0     1    0    0     4
[ 2  5  4  9  8  1  7  3 10  6]
fold
4     463
7     463
10    463
2     462
5     462
9     462
8     462
1     462
3     462
6     462
Name: count, dtype: int64


In [4]:
#search all .csv extension files in the test_dataset
# for root, dirs, files in os.walk(test_data_dir):
#     for file in files:
#         if file.endswith('.csv'):
#             print(file)

#from test_dataset
test_labels = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels.csv')
print(test_labels.head())

#count unique values in the classes
for c in classes:
    print(f'{c}: {test_labels[c].sum()}')






  patient_id  PAC  RBBB  LBBB  PVC  STD  AF  IAVB  STE  SNR  fold
0    JS00001    0     1     0    0    0   1     0    0    0     2
1    JS00005    0     0     0    0    1   0     0    0    0     5
2    JS00007    0     0     0    0    0   1     0    0    0     5
3    JS00008    0     0     0    0    0   0     0    0    1     5
4    JS00013    0     0     0    0    0   0     1    0    0     4
SNR: 1826
AF: 1780
IAVB: 247
LBBB: 205
RBBB: 454
PAC: 258
PVC: 0
STD: 402
STE: 176


In [7]:
#from train_dataset
test_labels = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/train_dataset/labels.csv')
print(test_labels.head())
classes = ['SNR', 'AF', 'IAVB', 'LBBB', 'RBBB', 'PAC', 'PVC', 'STD', 'STE']
#count unique values in the classes
for c in classes:
    print(f'{c}: {test_labels[c].sum()}')

  patient_id  PAC  RBBB  LBBB  PVC  STD  AF  IAVB  STE  SNR  fold
0      A0001    0     1     0    0    0   0     0    0    0     8
1      A0002    0     0     0    0    0   0     0    0    1     1
2      A0003    0     0     0    0    0   1     0    0    0     6
3      A0004    0     0     0    0    0   1     0    0    0     2
4      A0005    0     0     0    1    0   0     0    0    0     1
SNR: 19014
AF: 2888
IAVB: 1625
LBBB: 810
RBBB: 2513
PAC: 1295
PVC: 1854
STD: 1935
STE: 314


In [5]:
#make a duplcated copy of the labels.csv file in test_dataset
import shutil
shutil.copy('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels.csv', '/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv')
#alter the labels_altered.csv
test_labels = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv')
#duplicate last row of the labels_altered.csv
test_labels = pd.concat([test_labels,test_labels.iloc[-1]], ignore_index=True)
#alter PVC value of the last row to 1
test_labels.loc[test_labels.index[-1], 'PVC'] = 1
#verify count unique values in the classes
for c in classes:
    print(f'{c}: {test_labels[c].sum()}')
#save the altered labels
test_labels.to_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv', index=False)

SNR: 1826.0
AF: 1780.0
IAVB: 247.0
LBBB: 205.0
RBBB: 454.0
PAC: 258.0
PVC: 1.0
STD: 402.0
STE: 176.0


In [10]:
#count unique values in the folds
print(test_labels['fold'].value_counts())

fold
4     463
7     463
10    463
2     462
5     462
9     462
8     462
1     462
3     462
6     462
Name: count, dtype: int64


In [9]:
import numpy as np
from collections import Counter

#load the y_trues and y_scores from file txt
y_trues_test = np.loadtxt('/workspaces/ecg-arrhythmia-model/y_trues_test.txt')
y_scores_test = np.loadtxt('/workspaces/ecg-arrhythmia-model/y_scores_test.txt')


# Convert one-hot encoded y_true to class labels
y_true_classes_test = np.argmax(y_trues_test, axis=1)

# Check class distribution
class_distribution_test = Counter(y_true_classes_test)
print("Class distribution in y_true:", class_distribution_test)

# Identify problematic classes
for class_index in range(y_trues_test.shape[1]):
    class_true = y_trues_test[:, class_index]
    unique_values = np.unique(class_true)
    if len(unique_values) == 1:
        print(f"Class {class_index} has only one unique value: {unique_values[0]}")

#get the name of the classes index 6
# Load the class names
class_names = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv').columns[1:]        
print(class_names[6])

# Load few rows of the labels_altered.csv
labels = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv')
print(labels.head())

#count unique values in the classes
for c in classes:
    print(f'{c}: {labels[c].sum()}')
    
#alter the labels_altered.csv to make the PVC class not unique
#duplicate last row of the labels_altered.csv
labels = pd.concat([labels, labels.iloc[-1]], ignore_index=True)



Class distribution in y_true: Counter({0: 1826, 1: 1780, 4: 248, 2: 217, 5: 194, 7: 152, 3: 121, 8: 85})
Class 6 has only one unique value: 0.0
IAVB
  patient_id  PAC  RBBB  LBBB  PVC  STD   AF  IAVB  STE  SNR  fold    0
0    JS00001  0.0   1.0   0.0  0.0  0.0  1.0   0.0  0.0  0.0   2.0  NaN
1    JS00005  0.0   0.0   0.0  0.0  1.0  0.0   0.0  0.0  0.0   5.0  NaN
2    JS00007  0.0   0.0   0.0  0.0  0.0  1.0   0.0  0.0  0.0   5.0  NaN
3    JS00008  0.0   0.0   0.0  0.0  0.0  0.0   0.0  0.0  1.0   5.0  NaN
4    JS00013  0.0   0.0   0.0  0.0  0.0  0.0   1.0  0.0  0.0   4.0  NaN
SNR: 1826.0
AF: 1780.0
IAVB: 247.0
LBBB: 205.0
RBBB: 454.0
PAC: 258.0
PVC: 1.0
STD: 402.0
STE: 176.0


In [11]:
import numpy as np
from collections import Counter

#load the y_trues and y_scores from file txt
y_trues_org = np.loadtxt('/workspaces/ecg-arrhythmia-model/y_trues_org.txt')
y_scores_org = np.loadtxt('/workspaces/ecg-arrhythmia-model/y_scores_org.txt')


# Convert one-hot encoded y_true to class labels
y_true_classes_org = np.argmax(y_trues_org, axis=1)

# Check class distribution
class_distribution_org = Counter(y_true_classes_org)
print("Class distribution in y_true:", class_distribution_org)

# Identify problematic classes
for class_index in range(y_trues_org.shape[1]):
    class_true = y_trues_org[:, class_index]
    unique_values = np.unique(class_true)
    if len(unique_values) == 1:
        print(f"Class {class_index} has only one unique value: {unique_values[0]}")





Class distribution in y_true: Counter({0: 1908, 1: 297, 4: 182, 2: 113, 6: 86, 7: 79, 5: 69, 3: 27, 8: 22})


In [12]:
#print y_trues_test few rows
print(y_trues_test[:5])

#print labels_altered.csv shape
print(labels.shape)

[[0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]]
(4646, 13)


In [6]:
#load 05 rows of labels.csv from test_dataset
labels_test = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels.csv')
# print(labels_test.head())
#load 05 rows of train_dataset/labels.csv where folds = 9
labels_train = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/train_dataset/labels.csv')
# print(labels_train[labels_train['fold'] == 9].head())

#structure of the labels_altered.csv
print(labels_test.shape)
#structure of the train_dataset/labels.csv
print(labels_train[labels_train['fold'] == 9].shape)

#count unique values in the class of labels_train, fold 9
print("Label distribution in the train dataset, fold 9:")
for c in classes:    
    print(f'{c}: {labels_train[labels_train["fold"] == 9][c].sum()}')
print("Label distribution in the test dataset:")
for c in classes:    
    print(f'{c}: {labels_test[c].sum()}')


(4623, 11)
(2782, 11)
Label distribution in the train dataset, fold 9:


NameError: name 'classes' is not defined

In [15]:
#delete file labels_altered.csv if it exists
if os.path.exists('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv'):
    os.remove('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv')
#make new labels_altered.csv with the same content as labels.csv in test_dataset
shutil.copy('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels.csv', '/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv')
#update top 200 SNR records of labels_altered.csv to have PVC = 1, others = 0
labels = pd.read_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv')
labels.loc[labels['SNR'] == 1, 'PVC'] = 1
labels.loc[labels['SNR'] == 1, 'AF'] = 0
labels.loc[labels['SNR'] == 1, 'IAVB'] = 0
labels.loc[labels['SNR'] == 1, 'LBBB'] = 0
labels.loc[labels['SNR'] == 1, 'RBBB'] = 0
labels.loc[labels['SNR'] == 1, 'PAC'] = 0
labels.loc[labels['SNR'] == 1, 'STD'] = 0
labels.loc[labels['SNR'] == 1, 'STE'] = 0
#save the altered labels
labels.to_csv('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv', index=False)

#check distribution of the classes in the altered labels
print("Label distribution in the test dataset:")
for c in classes:    
    print(f'{c}: {labels[c].sum()}')


Label distribution in the test dataset:
SNR: 1826
AF: 1780
IAVB: 217
LBBB: 194
RBBB: 428
PAC: 222
PVC: 1826
STD: 372
STE: 157


In [2]:
import shutil
# #duplicate labels_altered.csv from test_dataset to train_dataset
# shutil.copy('/workspaces/ecg-arrhythmia-model/data/test_dataset/labels_altered.csv', '/workspaces/ecg-arrhythmia-model/data/train_dataset/labels_altered.csv')

'/workspaces/ecg-arrhythmia-model/data/train_dataset/labels_altered.csv'

In [12]:
#compare structure, distribution of labels.csv in train_dataset and labels.csv in test_dataset
#structure of the labels.csv in test_dataset
print(labels_test.shape)
#structure of the labels.csv in train_dataset
print(labels_train[labels_train['fold'] == 9].shape)
#count unique values in the classes
print("Label distribution in the train dataset:")
for c in classes:    
    print(f'{c}: {labels_train[labels_train["fold"] == 9][c].sum()}')
print("Label distribution in the test dataset:")
for c in classes:    
    print(f'{c}: {labels_test[c].sum()}')
#print the first few rows of the labels.csv in test_dataset
print(labels_test.head())
#print the first few rows of the labels.csv in train_dataset
print(labels_train[labels_train['fold'] == 9].head())

(4623, 11)
(2782, 11)
Label distribution in the train dataset:
SNR: 1915
AF: 307
IAVB: 169
LBBB: 76
RBBB: 245
PAC: 128
PVC: 179
STD: 193
STE: 32
Label distribution in the test dataset:
SNR: 1826
AF: 1780
IAVB: 247
LBBB: 205
RBBB: 454
PAC: 258
PVC: 0
STD: 402
STE: 176
  patient_id  PAC  RBBB  LBBB  PVC  STD  AF  IAVB  STE  SNR  fold
0    JS00001    0     1     0    0    0   1     0    0    0     2
1    JS00005    0     0     0    0    1   0     0    0    0     5
2    JS00007    0     0     0    0    0   1     0    0    0     5
3    JS00008    0     0     0    0    0   0     0    0    1     5
4    JS00013    0     0     0    0    0   0     1    0    0     4
   patient_id  PAC  RBBB  LBBB  PVC  STD  AF  IAVB  STE  SNR  fold
15      A0016    0     0     0    0    0   0     0    0    1     9
19      A0020    0     0     0    0    0   0     0    0    1     9
28      A0029    0     0     0    0    0   0     0    0    1     9
46      A0047    1     0     0    0    0   0     0    0    0     9
5